/*
 * Notifications API
 *
 * Notifications API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type Params struct {

	// [required] #email;  E-mail addresses 
	Addresses []string `json:"addresses,omitempty"`

	// [required] #webhook;  Webhook URL 
	Url string `json:"url,omitempty"`

	// [optional] #webhook;  HTTP method; default: POST (GET, POST) 
	Method string `json:"method,omitempty"`

	// [optional] #webhook;  Number of retries before forgetting the notification; default: 0 
	Retries int32 `json:"retries,omitempty"`

	// [optional] #webhook; default: application/json (application/json, application/x-www-form-urlencoded) 
	ContentType string `json:"content_type,omitempty"`
}
