/*
 * Notifications API
 *
 * Notifications API V2
 *
 * API version: 2.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type Params struct {

	// (for email subscription type);  E-mail addresses 
	Addresses []string `json:"addresses,omitempty"`

	// (for webhook subscription type);  Webhook URL 
	Url string `json:"url,omitempty"`

	// (for webhook subscription type);  HTTP method; default: POST (GET, POST) 
	Method string `json:"method,omitempty"`

	// (for webhook subscription type);  Number of retries before forgetting the notification; default: 0 
	Retries int32 `json:"retries,omitempty"`

	// (for webhook subscription type); default: application/json (application/json, application/x-www-form-urlencoded) 
	ContentType string `json:"content_type,omitempty"`

	// (for sns subscription type) identifier of an AWS SNS Topic that events will be posted to. 
	TopicArn string `json:"topic_arn,omitempty"`

	// (for sns subscription type) identifier of an AWS IAM Role that will be used for authorization. 
	RoleArn string `json:"role_arn,omitempty"`

	// (for aeg subscription type) address of an Azure Event Grid Topic that events will be posted to. 
	TopicEndpoint string `json:"topic_endpoint,omitempty"`

	// (for aeg subscription type) secret access key that authorizes Telestream Cloud to write to an Azure Event Grid Topic. 
	AccessKey string `json:"access_key,omitempty"`

	// (for pubsub subscription type) id of a Google Cloud project that hosts the topic. 
	ProjectId string `json:"project_id,omitempty"`

	// (for pubsub subscription type) name of a Google Cloud Pub/Sub topic to which notifications will be published. 
	TopicName string `json:"topic_name,omitempty"`
}
