/*
 * Notifications API
 *
 * Notifications API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type Subscription struct {

	// [read-only] Subscription identifier 
	Id string `json:"id,omitempty"`

	// [required] Type of subscription (email, webhook) 
	Type_ string `json:"type,omitempty"`

	// [required] 
	Topic *Topic `json:"topic,omitempty"`

	// [required] 
	Params *Params `json:"params,omitempty"`
}
