/*
 * Notifications API
 *
 * Notifications API V2
 *
 * API version: 2.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type Subscription struct {

	// [read-only] Subscription identifier 
	Id string `json:"id,omitempty"`

	// Type of subscription (email, webhook, sns, aeg, pubsub) 
	Type_ string `json:"type"`

	Topic *Topic `json:"topic"`

	Params *Params `json:"params"`
}
