/*
 * Notifications API
 *
 * Notifications API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type Topic struct {

	// [read-only] Account identifier connected to subscription notification 
	Account string `json:"account,omitempty"`

	// [required] Name of service 
	Service string `json:"service,omitempty"`

	// [required] Name of the event;  Quality Control (video-passed,  video-error,  video-warning,  video-rejected,  video-canceled) 
	Event string `json:"event,omitempty"`

	// [required] Project ID 
	Project string `json:"project,omitempty"`
}
