/*
 * Notifications API
 *
 * Notifications API V2
 *
 * API version: 2.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package notifications

type UpdateData struct {

	Topic *UpdateTopic `json:"topic,omitempty"`

	Params *Params `json:"params,omitempty"`
}
