/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type ErrorResponse struct {

	Errors []ModelError `json:"errors,omitempty"`
}
