/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type ObjectUrl struct {

	Url string `json:"url,omitempty"`
}
