/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type Output struct {

	Id string `json:"id,omitempty"`

	PathFormat string `json:"path_format,omitempty"`

	StoreId string `json:"store_id,omitempty"`

	ServiceId string `json:"service_id,omitempty"`

	ServiceName string `json:"service_name,omitempty"`
}
