/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type StoreBody struct {

	Name string `json:"name"`

	Provider string `json:"provider"`

	BucketName string `json:"bucket_name"`

	Region string `json:"region"`

	PrivateAccess bool `json:"private_access,omitempty"`

	AccessKey string `json:"access_key"`

	SecretKey string `json:"secret_key"`

	ProviderSpecificSettings *StoreBodyProviderSpecificSettings `json:"provider_specific_settings,omitempty"`
}
