/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type Store struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name,omitempty"`

	Provider string `json:"provider,omitempty"`

	AccountId string `json:"account_id,omitempty"`

	BucketName string `json:"bucket_name,omitempty"`

	InputStore bool `json:"input_store,omitempty"`

	WatchInterval int32 `json:"watch_interval,omitempty"`

	Region string `json:"region,omitempty"`

	PrivateAccess bool `json:"private_access,omitempty"`

	AccessKey string `json:"access_key,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`

	BaseUploadUrl string `json:"base_upload_url,omitempty"`

	ProviderSpecificSettings *StoreBodyProviderSpecificSettings `json:"provider_specific_settings,omitempty"`
}
