/*
 * API
 *
 * API
 *
 * API version: 1.0.0
 * Contact: you@your-company.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package stores

type ValidateBucketBody struct {

	BucketName string `json:"bucket_name,omitempty"`

	Provider string `json:"provider,omitempty"`

	Region string `json:"region,omitempty"`

	AccessKey string `json:"access_key,omitempty"`

	SecretKey string `json:"secret_key,omitempty"`
}
