/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type CanceledResponse struct {

	// Informs whether an action has been canceled successfully.
	Canceled bool `json:"canceled,omitempty"`
}
