/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type CanceledResponse struct {

	// Informs whether an action has been canceled successfully.
	Canceled bool `json:"canceled,omitempty"`
}
