/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type CloudNotificationSettings struct {

	// Notifications will be sent to this endpoint.
	Url string `json:"url"`

	Delay int32 `json:"delay"`

	// Determines whether a video payload will be included in notification messages.
	SendVideoPayload bool `json:"send_video_payload"`

	Events CloudNotificationSettingsEvents `json:"events,omitempty"`
}
