/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type CloudNotificationSettings struct {

	// Notifications will be sent to this endpoint.
	Url string `json:"url"`

	Delay int32 `json:"delay"`

	// Determines whether a video payload will be included in notification messages.
	SendVideoPayload bool `json:"send_video_payload"`

	Events *CloudNotificationSettingsEvents `json:"events"`
}
