/*
 * Flip API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type CloudNotificationSettingsEvents struct {

	// If set to `true`, a notification will be sent after an encoding becomes complete.
	EncodingCompleted bool `json:"encoding_completed"`

	// If set to `true`, a notification will be sent after an encoding's progess changes.
	EncodingProgress bool `json:"encoding_progress"`

	// If set to `true`, a notification will be sent after a video is created.
	VideoCreated bool `json:"video_created"`

	// If set to `true`, a notification will be sent after a video is encoded.
	VideoEncoded bool `json:"video_encoded"`
}
