/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type CopyProfileBody struct {

	// an id of a target Factory that will own a copy of the Profile
	DestFactoryId string `json:"dest_factory_id"`

	// a name for a copy of the Profile
	ProfileName string `json:"profile_name"`
}
