/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type CountResponse struct {

	// Informs how many objects are stored in the database.
	Total int32 `json:"total,omitempty"`
}
