/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type CreateVideoBody struct {

	// An URL pointing to a source file.
	SourceUrl string `json:"source_url,omitempty"`

	// Comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings are created yet.
	Profiles string `json:"profiles,omitempty"`

	// Payload is an arbitrary text of length 256 or shorter that you can store along the Video. It is typically used to retain an association with one of your own DB record ID.
	Payload string `json:"payload,omitempty"`

	// String-encoded JSON describing profiles pipeline.
	Pipeline string `json:"pipeline,omitempty"`

	// A list of urls pointing to remote subtitle files.
	SubtitleFiles []string `json:"subtitle_files,omitempty"`
}
