/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type DeletedResponse struct {

	// Informs whether an object has been deleted successfully.
	Deleted bool `json:"deleted,omitempty"`
}
