/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type DeletedResponse struct {

	// Informs whether an object has been deleted successfully.
	Deleted bool `json:"deleted,omitempty"`
}
