/*
 * Flip API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type EncodingSignedUrl struct {

	// A signed URLs pointing to the encoding's output.
	SignedUrl string `json:"signed_url,omitempty"`
}
