/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type EncodingSignedUrls struct {

	// A list of signed URLs pointing to the encoding's outputs.
	SignedUrls []string `json:"signed_urls,omitempty"`
}
