/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type FactoryBodyStorageCredentialAttributes struct {

	Host string `json:"host,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Port int32 `json:"port,omitempty"`
}
