/*
 * Flip API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type FactorySyncBody struct {

	// Determines whether a Factory's data will be synchronised.
	Sync string `json:"sync"`
}
