/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type FactorySync struct {

	// Determines whether a Factory will be synchronised with an input bucket.
	Syncing string `json:"syncing,omitempty"`
}
