/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type FactoryBodyStorageCredentialAttributes struct {

	Host string `json:"host,omitempty"`

	Username string `json:"username,omitempty"`

	Password string `json:"password,omitempty"`

	Port int32 `json:"port,omitempty"`
}
