/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type FactorySync struct {

	// Determines whether a Factory will be synchronised with an input bucket.
	Syncing string `json:"syncing,omitempty"`
}
