/*
 * Flip API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type ModelError struct {

	// Error type
	Error_ string `json:"error,omitempty"`

	// Explanation why the error has been raised.
	Message string `json:"message,omitempty"`
}
