/*
 * Flip API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type PaginatedProfilesCollection struct {

	Profiles []Profile `json:"profiles,omitempty"`

	// A number of the fetched page.
	Page int32 `json:"page,omitempty"`

	// A number of profiles per page.
	PerPage int32 `json:"per_page,omitempty"`

	// A number of all profiles stored in the db.
	Total int32 `json:"total,omitempty"`
}
