/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type PaginatedWorkflowsCollection struct {

	Workflows []Profile `json:"workflows,omitempty"`

	// A number of the fetched page.
	Page int32 `json:"page,omitempty"`

	// A number of factories per page.
	PerPage int32 `json:"per_page,omitempty"`

	// A number of all factories stored in the db.
	Total int32 `json:"total,omitempty"`
}
