/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type ResubmitVideoBody struct {

	// Id of the video.
	VideoId string `json:"video_id,omitempty"`
}
