/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type RetriedResponse struct {

	// Informs whether an action has been retried successfully.
	Retried bool `json:"retried,omitempty"`
}
