/*
 * Flip API
 *
 * Description
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flip

type RetriedResponse struct {

	// Informs whether an action has been retried successfully.
	Retried bool `json:"retried,omitempty"`
}
