/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type SignedVideoUrl struct {

	// An URL pointing to the Video file. It contains a valid authentication token.
	SignedUrl string `json:"signed_url,omitempty"`
}
