/* 
 * Flip API
 *
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package flip

type UpdateEncodingBody struct {

	// Id of a Profile that will be used for encoding.
	ProfileId string `json:"profile_id,omitempty"`

	// A name of a Profile that will be used for encoding.
	ProfileName string `json:"profile_name,omitempty"`
}
