/*
 * IAM API
 *
 * IAM API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package iam

type Credential struct {

	Id string `json:"id,omitempty"`

	ApiKey string `json:"api_key,omitempty"`

	Tag string `json:"tag,omitempty"`

	Policy *interface{} `json:"policy,omitempty"`

	ParentCredentialId int32 `json:"parent_credential_id,omitempty"`
}
