/*
 * IAM API
 *
 * IAM API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package iam

// Error response
type ModelError struct {

	Error_ string `json:"error,omitempty"`
}
