/*
 * IAM API
 *
 * IAM API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package iam

type Policy struct {

	Statements []Statement `json:"statements,omitempty"`

	Version int32 `json:"version,omitempty"`
}
