/*
 * IAM API
 *
 * IAM API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package iam

type Statement struct {

	Effect string `json:"effect,omitempty"`

	Action string `json:"action,omitempty"`

	Resource string `json:"resource,omitempty"`
}
