/*
 * Tts API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type Corpus struct {

	// The name of the Corpus.
	Name string `json:"name,omitempty"`

	// Determines the status of the Corpus.
	Status string `json:"status,omitempty"`
}
