/*
 * Tts API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type CorporaCollection struct {

	// An array of Corpus files
	Corpora []Corpus `json:"corpora,omitempty"`
}
