/*
 * Tts API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type ExtraFile struct {

	Tag string `json:"tag"`

	FileSize int64 `json:"file_size"`

	FileName string `json:"file_name"`
}
