/*
 * Tts API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type Fragment struct {

	// The start time in seconds of the fragment from the input audio
	StartTime float32 `json:"start_time,omitempty"`

	// An array of FragmentVariants
	Variants []FragmentVariant `json:"variants,omitempty"`

	// The end time in seconds of the fragment from the input audio
	EndTime float32 `json:"end_time,omitempty"`
}
