/*
 * Tts API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type Job struct {

	// The ID of the job.
	Id string `json:"id,omitempty"`

	// The name of the job.
	Name string `json:"name,omitempty"`

	// The name of the input file
	OriginalFilename string `json:"original_filename,omitempty"`

	// The ID of the project.
	ProjectId string `json:"project_id,omitempty"`

	// The URL of source file.
	SourceUrl string `json:"source_url,omitempty"`

	// Determines the state of transcription job.
	Status string `json:"status,omitempty"`

	// If the status of the job is 'error', returns the state of job.
	Error_ string `json:"error,omitempty"`

	// A percentage that indicates the progress of the job.
	Progress int32 `json:"progress,omitempty"`

	// The confidence score of the job in the range of 0 to 100.
	Confidence int32 `json:"confidence,omitempty"`

	// The duration of the input audio in milliseconds.
	Duration int32 `json:"duration,omitempty"`

	// The bitrate of the input audio.
	Bitrate int32 `json:"bitrate,omitempty"`

	// The sample rate of the input audio.
	SampleRate int32 `json:"sample_rate,omitempty"`

	// The format of the input audio.
	Format string `json:"format,omitempty"`

	// The file size of the input file.
	FileSize string `json:"file_size,omitempty"`

	// A date and time when the job was created
	CreatedAt string `json:"created_at,omitempty"`

	// A date and time when the job was updated
	UpdatedAt string `json:"updated_at,omitempty"`
}
