/*
 * Tts API
 *
 * Description
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type JobOutput struct {

	// Output file format
	Format string `json:"format,omitempty"`

	// URL to output (must be accessed with X-Api-Key)
	Url string `json:"url,omitempty"`
}
