/*
 * Tts API
 *
 * Description
 *
 * API version: 3.1.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package tts

type JobsCollection struct {

	Jobs []Job `json:"jobs,omitempty"`

	// A number of the fetched page.
	Page int32 `json:"page,omitempty"`

	// A number of jobs per page.
	PerPage int32 `json:"per_page,omitempty"`

	// A number of pages.
	PageCount int32 `json:"page_count,omitempty"`

	// A number of all jobs.
	TotalCount int32 `json:"total_count,omitempty"`
}
