/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type AudioStream struct {

	// Audio duration measured in seconds.
	Duration float32 `json:"duration,omitempty"`

	// Audio codec name.
	Codec string `json:"codec,omitempty"`

	// Number of audio channels.
	Channels int32 `json:"channels,omitempty"`

	Program string `json:"program,omitempty"`

	// Audio bitrate measured in bps
	Bitrate int32 `json:"bitrate,omitempty"`

	// Sample rate measured in Hz.
	SampleRate int32 `json:"sample_rate,omitempty"`
}
