/*
 * Qc API
 *
 * QC API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Container struct {

	Type_ string `json:"type,omitempty"`

	// File bitrate measured in bps
	Bitrate string `json:"bitrate,omitempty"`
}
