/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type Data struct {

	// Human-readable identifier of a Project.
	Name string `json:"name,omitempty"`

	// Name of QC template 1.
	Template string `json:"template,omitempty"`

	Options Options `json:"options,omitempty"`
}
