/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type Data1 struct {

	Name string `json:"name,omitempty"`

	Options Options `json:"options,omitempty"`
}
