/*
 * Qc API
 *
 * QC API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Data1 struct {

	Name string `json:"name,omitempty"`

	Options *Options `json:"options,omitempty"`
}
