/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type ExtraFile struct {

	Tag string `json:"tag"`

	FileSize int64 `json:"file_size"`

	FileName string `json:"file_name"`
}
