/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.3
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type InlineResponse200 struct {

	ProjectName string `json:"project_name,omitempty"`

	ProjectId string `json:"project_id,omitempty"`
}
