/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Job struct {

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	State string `json:"state,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	Type_ string `json:"type,omitempty"`

	Progress int32 `json:"progress,omitempty"`

	Filename string `json:"filename,omitempty"`

	SourceUrl string `json:"source_url,omitempty"`

	CreatedAt string `json:"created_at,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`

	ErrorClass string `json:"error_class,omitempty"`

	ErrorMessage string `json:"error_message,omitempty"`

	Details *JobDetails `json:"details,omitempty"`
}
