/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type Job struct {

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	Type_ string `json:"type,omitempty"`

	Details JobDetails `json:"details,omitempty"`
}
