/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Job struct {

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	Duration int32 `json:"duration,omitempty"`

	Type_ string `json:"type,omitempty"`

	Details *JobDetails `json:"details,omitempty"`
}
