/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type JobData struct {

	Options *Options `json:"options,omitempty"`

	Url string `json:"url,omitempty"`

	// Payload is an arbitrary text of length 256 or shorter that you can store along the Media. It is typically used to retain an association with one of your own DB record ID.
	Payload string `json:"payload,omitempty"`
}
