/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type JobDetails struct {

	Media []Media `json:"media,omitempty"`

	Result *JobDetailsResult `json:"result,omitempty"`
}
