/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type JobDetails struct {

	Media []Media `json:"media,omitempty"`

	Result JobDetailsResult `json:"result,omitempty"`
}
