/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

// Description of the processed media file.
type Media struct {

	Audio []AudioStream `json:"audio,omitempty"`

	Video []VideoStream `json:"video,omitempty"`

	Container *Container `json:"container,omitempty"`
}
