/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

// Description of the processed media file.
type Media struct {

	Audio []AudioStream `json:"audio,omitempty"`

	Video []VideoStream `json:"video,omitempty"`

	Container Container `json:"container,omitempty"`
}
