/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ExtraAudioLayoutModes string

// List of extra_audio_layout_modes
const (
	EXTRAAUDIOLAYOUTMODES_NONE ExtraAudioLayoutModes = "EXTRA-AUDIO-MODES-NONE"
	EXTRAAUDIOLAYOUTMODES__1 ExtraAudioLayoutModes = "EXTRA-AUDIO-MODES-1"
	EXTRAAUDIOLAYOUTMODES__1_AND_2 ExtraAudioLayoutModes = "EXTRA-AUDIO-MODES-1-AND-2"
)