/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ColorSpaceType string

// List of color_space_type
const (
	COLORSPACETYPE_CS_UNKNOWN ColorSpaceType = "CSUnknown"
	COLORSPACETYPE_CSBT601 ColorSpaceType = "CSBT601"
	COLORSPACETYPE_CSBT709 ColorSpaceType = "CSBT709"
	COLORSPACETYPE_CSBT2020 ColorSpaceType = "CSBT2020"
)