/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VideoUploadBody struct {
	// Size of the file that will be uploaded in `bytes`.
	FileSize int64 `json:"file_size"`
	// Name of the file that will be uploaded.
	FileName string `json:"file_name"`
	// A list of names of additional files that will be uploaded.
	ExtraFiles []ExtraFile `json:"extra_files,omitempty"`
	// A comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings will created right away.
	Profiles string `json:"profiles,omitempty"`
	MultiChunk bool `json:"multi_chunk,omitempty"`
}
