/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type VideoDescriptorType string

// List of video_descriptor_type
const (
	VIDEODESCRIPTORTYPE_MPEG_DESCRIPTOR VideoDescriptorType = "MpegDescriptor"
)