/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ArrayOfSoundEssenceCoding struct {
	SoundEssenceCoding []SoundEssenceCoding `json:"sound_essence_coding,omitempty"`
}
