/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type GopReport string

// List of gop_report
const (
	GOPREPORT_UNIQUE GopReport = "Unique"
	GOPREPORT_ALL GopReport = "All"
)