/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ModifyVidChecker8Body struct {
	Name string `json:"name,omitempty"`
	Options Vidchecker8 `json:"options,omitempty"`
}
