/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type SingleColorTest struct {
	MaxTimeAllowed float64 `json:"max_time_allowed,omitempty"`
	TimeSecsOrFrames SecsOrFramesType `json:"time_secs_or_frames,omitempty"`
	PercentageOfFrame float64 `json:"percentage_of_frame,omitempty"`
	IgnoreBelow int32 `json:"ignore_below,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
