/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type SecsOrFramesType string

// List of secs_or_frames_type
const (
	SECSORFRAMESTYPE_SECONDS SecsOrFramesType = "Seconds"
	SECSORFRAMESTYPE_FRAMES SecsOrFramesType = "Frames"
)