/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ForceColorSpaceTest struct {
	ColorSpace ColorSpaceType `json:"color_space,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
