/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type TimeCodeSource string

// List of time_code_source
const (
	TIMECODESOURCE_CONTAINER TimeCodeSource = "Container"
	TIMECODESOURCE_ELEMENTARY_STREAM TimeCodeSource = "ElementaryStream"
)