/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ChromaSubsampling string

// List of chroma_subsampling
const (
	CHROMASUBSAMPLING_UNKNOWN_CHROMA_SUBSAMPLING ChromaSubsampling = "UnknownChromaSubsampling"
	CHROMASUBSAMPLING_CHROMA420 ChromaSubsampling = "Chroma420"
	CHROMASUBSAMPLING_CHROMA422 ChromaSubsampling = "Chroma422"
	CHROMASUBSAMPLING_CHROMA444 ChromaSubsampling = "Chroma444"
	CHROMASUBSAMPLING_CHROMA411 ChromaSubsampling = "Chroma411"
)