/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type PartitionStatusTest struct {
	ClosedComplete bool `json:"closed_complete,omitempty"`
	OpenIncomplete bool `json:"open_incomplete,omitempty"`
	ClosedIncomplete bool `json:"closed_incomplete,omitempty"`
	OpenComplete bool `json:"open_complete,omitempty"`
	NotPresent bool `json:"not_present,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
