/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type BlankingTest struct {
	BlackLevelDefaultOrCustom DefaultOrCustomType `json:"black_level_default_or_custom,omitempty"`
	BlackLevel int32 `json:"black_level,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
