/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type DefaultOrCustomType string

// List of default_or_custom_type
const (
	DEFAULTORCUSTOMTYPE_DEFAULT DefaultOrCustomType = "Default"
	DEFAULTORCUSTOMTYPE_CUSTOM DefaultOrCustomType = "Custom"
	DEFAULTORCUSTOMTYPE_TEMPLATE DefaultOrCustomType = "Template"
)