/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type As11XprofileTest struct {
	As11Rules As11Rules `json:"as11_rules,omitempty"`
	EmbeddedXmlDocuments EmbeddedXmlDocuments `json:"embedded_xml_documents,omitempty"`
	ExtraAudioLayoutModes ExtraAudioLayoutModes `json:"extra_audio_layout_modes,omitempty"`
	PictureEssenceConstraints PictureEssenceConstraints `json:"picture_essence_constraints,omitempty"`
	FileFormatSpecificationIdentificationLabel FileFormatSpecificationIdentificationLabel `json:"file_format_specification_identification_label,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
