/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VideoCodecTest struct {
	VideoCodec VideoCodecType `json:"video_codec,omitempty"`
	VideoProfile VideoProfileType `json:"video_profile,omitempty"`
	VideoLevel VideoLevelType `json:"video_level,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
