/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type TeletextType string

// List of teletext_type
const (
	TELETEXTTYPE_TELETEXT_ANY TeletextType = "TeletextAny"
	TELETEXTTYPE_TELETEXT_OP47 TeletextType = "TeletextOp47"
)