/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type FreezeFrameTest struct {
	Sensitivity SensitivityType `json:"sensitivity,omitempty"`
	TimeRangeEnabled bool `json:"time_range_enabled,omitempty"`
	StartTime float64 `json:"start_time,omitempty"`
	EndTime float64 `json:"end_time,omitempty"`
	StartRangeTolerance float64 `json:"start_range_tolerance,omitempty"`
	TimeSecsOrFrames SecsOrFramesType `json:"time_secs_or_frames,omitempty"`
	EndRangeEnabled bool `json:"end_range_enabled,omitempty"`
	EndRange float64 `json:"end_range,omitempty"`
	EndRangeDuration float64 `json:"end_range_duration,omitempty"`
	EndRangeTolerance float64 `json:"end_range_tolerance,omitempty"`
	EndSecsOrFrames SecsOrFramesType `json:"end_secs_or_frames,omitempty"`
	NotAtAnyOtherTime bool `json:"not_at_any_other_time,omitempty"`
	MaxTimeAllowed float64 `json:"max_time_allowed,omitempty"`
	MaxTimeAllowedSecsOrFrames SecsOrFramesType `json:"max_time_allowed_secs_or_frames,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
