/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type LayoutType string

// List of layout_type
const (
	LAYOUTTYPE_LAYOUT_TYPE_FIXED_IGNORE_START_AND_END LayoutType = "LayoutTypeFixedIgnoreStartAndEnd"
	LAYOUTTYPE_LAYOUT_TYPE_TIMECODE_IGNORE_BEFORE_AND_AFTER LayoutType = "LayoutTypeTimecodeIgnoreBeforeAndAfter"
	LAYOUTTYPE_LAYOUT_TYPE_COPY_VIDEO LayoutType = "LayoutTypeCopyVideo"
	LAYOUTTYPE_LAYOUT_TYPE_FIXED_TEST_START LayoutType = "LayoutTypeFixedTestStart"
	LAYOUTTYPE_LAYOUT_TYPE_FIXED_TEST_END LayoutType = "LayoutTypeFixedTestEnd"
	LAYOUTTYPE_LAYOUT_TYPE_TIMECODE_TEST_BEFORE LayoutType = "LayoutTypeTimecodeTestBefore"
	LAYOUTTYPE_LAYOUT_TYPE_TIMECODE_TEST_AFTER LayoutType = "LayoutTypeTimecodeTestAfter"
)