/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type LoudnessMode string

// List of loudness_mode
const (
	LOUDNESSMODE_LOUDNESS_MODE_ITU LoudnessMode = "LoudnessModeItu"
	LOUDNESSMODE_LOUDNESS_MODE_EBU_M LoudnessMode = "LoudnessModeEbuM"
	LOUDNESSMODE_LOUDNESS_MODE_EBU_S LoudnessMode = "LoudnessModeEbuS"
	LOUDNESSMODE_LOUDNESS_MODE_EBU_I LoudnessMode = "LoudnessModeEbuI"
	LOUDNESSMODE_LOUDNESS_MODE_ARIB_B32 LoudnessMode = "LoudnessModeAribB32"
)