/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type FlashTest struct {
	CheckType PSeParameterType `json:"check_type,omitempty"`
	CheckForExtended bool `json:"check_for_extended,omitempty"`
	CheckForRed bool `json:"check_for_red,omitempty"`
	CheckForPatterns bool `json:"check_for_patterns,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
