/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type CaptionsTest struct {
	SignalEnabled bool `json:"signal_enabled,omitempty"`
	SignalTime float64 `json:"signal_time,omitempty"`
	SignalTimeSecsOrFrames SecsOrFramesType `json:"signal_time_secs_or_frames,omitempty"`
	ContentEnabled bool `json:"content_enabled,omitempty"`
	ContentTime float64 `json:"content_time,omitempty"`
	ContentTimeSecsOrFrames SecsOrFramesType `json:"content_time_secs_or_frames,omitempty"`
	Line21Cea608Enabled bool `json:"line21_cea608_enabled,omitempty"`
	A53Cea608Enabled bool `json:"a53_cea608_enabled,omitempty"`
	A53Cea708Enabled bool `json:"a53_cea708_enabled,omitempty"`
	Smpte436mCea608Enabled bool `json:"smpte436m_cea608_enabled,omitempty"`
	Smpte436mCea708Enabled bool `json:"smpte436m_cea708_enabled,omitempty"`
	StartDurationIgnore float64 `json:"start_duration_ignore,omitempty"`
	StartDurationSecsOrFrames SecsOrFramesType `json:"start_duration_secs_or_frames,omitempty"`
	EndDurationIgnore float64 `json:"end_duration_ignore,omitempty"`
	EndDurationSecsOrFrames SecsOrFramesType `json:"end_duration_secs_or_frames,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
