/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ExtraFile struct {
	Tag string `json:"tag"`
	FileSize int64 `json:"file_size"`
	FileName string `json:"file_name"`
}
