/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type MxfColorSiting string

// List of mxf_color_siting
const (
	MXFCOLORSITING_CO_SITING MxfColorSiting = "CoSiting"
	MXFCOLORSITING_HORIZONTAL_MIDPOINT MxfColorSiting = "HorizontalMidpoint"
	MXFCOLORSITING_THREE_TAP MxfColorSiting = "ThreeTap"
	MXFCOLORSITING_QUINCUNX MxfColorSiting = "Quincunx"
	MXFCOLORSITING_REC601 MxfColorSiting = "Rec601"
	MXFCOLORSITING_LINE_ALTERNATING MxfColorSiting = "LineAlternating"
	MXFCOLORSITING_VERTICAL_MIDPOINT MxfColorSiting = "VerticalMidpoint"
	MXFCOLORSITING_UNKNOWN MxfColorSiting = "Unknown"
)