/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type AudioMinLevelDurationTest struct {
	Level float64 `json:"level,omitempty"`
	Duration float64 `json:"duration,omitempty"`
	DurationSecsOrFrames SecsOrFramesType `json:"duration_secs_or_frames,omitempty"`
	Channels Channels `json:"channels,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
