/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type PixelAspectRatioTest struct {
	PixelAspectRatioNumerator int32 `json:"pixel_aspect_ratio_numerator,omitempty"`
	PixelAspectRatioDenominator int32 `json:"pixel_aspect_ratio_denominator,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
