/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type SensitivityType string

// List of sensitivity_type
const (
	SENSITIVITYTYPE_LOW SensitivityType = "Low"
	SENSITIVITYTYPE_MEDIUM SensitivityType = "Medium"
	SENSITIVITYTYPE_HIGH SensitivityType = "High"
)