/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type RequireOrDisallow string

// List of require_or_disallow
const (
	REQUIREORDISALLOW_REQUIRE RequireOrDisallow = "Require"
	REQUIREORDISALLOW_DISALLOW RequireOrDisallow = "Disallow"
)