/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type SidsAnyOrSpecific string

// List of sids_any_or_specific
const (
	SIDSANYORSPECIFIC_SIDS_ANY SidsAnyOrSpecific = "SidsAny"
	SIDSANYORSPECIFIC_SIDS_SPECIFIC SidsAnyOrSpecific = "SidsSpecific"
)