/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Summary struct {
	// Total number of synchronization detection events considered for summary.
	NumSyncEvents int32 `json:"num_sync_events,omitempty"`
	AvsyncAnalysis string `json:"avsync_analysis,omitempty"`
	AvsyncInference string `json:"avsync_inference,omitempty"`
	// Confidence of avsync_inference and avsync_analysis. 'confidence' is a value between 0 and 100. confidence >= 90  - Very high confidence. 80 <= confidence < 90   - High confidence. 70 <= confidence < 80   - Should be reviewed by human. 
	Confidence float32 `json:"confidence,omitempty"`
	// Skew estimate in #frames; Skew is the number of frames that audio is delayed to the video
	Skew int32 `json:"skew,omitempty"`
	TotalLength float32 `json:"total_length,omitempty"`
}
