/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type AvcSpsPpsTest struct {
	Profile int32 `json:"profile,omitempty"`
	ProfileConstraint int32 `json:"profile_constraint,omitempty"`
	SpsFlag int32 `json:"sps_flag,omitempty"`
	PpsFlag int32 `json:"pps_flag,omitempty"`
	Level int32 `json:"level,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
