/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type TrackSelectorType string

// List of track_selector_type
const (
	TRACKSELECTORTYPE_TRACK_INDEX TrackSelectorType = "TrackIndex"
	TRACKSELECTORTYPE_TRACK_ID TrackSelectorType = "TrackId"
	TRACKSELECTORTYPE_TRACK_USE_PREVIOUS TrackSelectorType = "TrackUsePrevious"
)