/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type AudioPpmLevelTest struct {
	MinPpmLevelEnabled bool `json:"min_ppm_level_enabled,omitempty"`
	MinPpmLevel float64 `json:"min_ppm_level,omitempty"`
	MaxPpmLevelEnabled bool `json:"max_ppm_level_enabled,omitempty"`
	MaxPpmLevel float64 `json:"max_ppm_level,omitempty"`
	Mode PpmMode `json:"mode,omitempty"`
	Channels Channels `json:"channels,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
