/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ChromaLevelTest struct {
	YLevelDefaultOrCustom DefaultOrCustomType `json:"y_level_default_or_custom,omitempty"`
	YLevelLower int32 `json:"y_level_lower,omitempty"`
	YLevelUpper int32 `json:"y_level_upper,omitempty"`
	YLevelMaxOutsideRange float32 `json:"y_level_max_outside_range,omitempty"`
	YLevelToleranceLow float32 `json:"y_level_tolerance_low,omitempty"`
	YLevelToleranceHigh float32 `json:"y_level_tolerance_high,omitempty"`
	UVlevelDefaultOrCustom DefaultOrCustomType `json:"u_vlevel_default_or_custom,omitempty"`
	UVlevelLower int32 `json:"u_vlevel_lower,omitempty"`
	UVlevelUpper int32 `json:"u_vlevel_upper,omitempty"`
	UVlevelMaxOutsideRange float32 `json:"u_vlevel_max_outside_range,omitempty"`
	LowPassFilter LowPassFilterType `json:"low_pass_filter,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
