/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VideoBitrateTest struct {
	VideoBitrateLower float64 `json:"video_bitrate_lower,omitempty"`
	VideoBitrateUpper float64 `json:"video_bitrate_upper,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
