/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type MxfVersion string

// List of mxf_version
const (
	MXFVERSION__2004 MxfVersion = "SMPTE-377-2004"
	MXFVERSION__2011 MxfVersion = "SMPTE-377-2011"
)