/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type LossOfChromaTest struct {
	LevelDefaultOrCustom DefaultOrCustomType `json:"level_default_or_custom,omitempty"`
	Level int32 `json:"level,omitempty"`
	Tolerance int32 `json:"tolerance,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
