/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type VideoProfileType string

// List of video_profile_type
const (
	VIDEOPROFILETYPE_VIDEO_PROFILE_NONE VideoProfileType = "VideoProfileNone"
	VIDEOPROFILETYPE_H264_BASELINE VideoProfileType = "H264Baseline"
	VIDEOPROFILETYPE_H264_MAIN VideoProfileType = "H264Main"
	VIDEOPROFILETYPE_H264_EXTENDED VideoProfileType = "H264Extended"
	VIDEOPROFILETYPE_H264_HIGH VideoProfileType = "H264High"
	VIDEOPROFILETYPE_H264_HIGH10 VideoProfileType = "H264High10"
	VIDEOPROFILETYPE_H264_HIGH422 VideoProfileType = "H264High422"
	VIDEOPROFILETYPE_H264_HIGH444 VideoProfileType = "H264High444"
	VIDEOPROFILETYPE_H264_HIGH10_INTRA VideoProfileType = "H264High10Intra"
	VIDEOPROFILETYPE_H264_HIGH422_INTRA VideoProfileType = "H264High422Intra"
	VIDEOPROFILETYPE_H264_HIGH444_INTRA VideoProfileType = "H264High444Intra"
	VIDEOPROFILETYPE_MPEG2_SIMPLE VideoProfileType = "Mpeg2Simple"
	VIDEOPROFILETYPE_MPEG2_MAIN VideoProfileType = "Mpeg2Main"
	VIDEOPROFILETYPE_MPEG2_SNR VideoProfileType = "Mpeg2Snr"
	VIDEOPROFILETYPE_MPEG2_SPATIAL VideoProfileType = "Mpeg2Spatial"
	VIDEOPROFILETYPE_MPEG2_HIGH VideoProfileType = "Mpeg2High"
	VIDEOPROFILETYPE_MPEG2422 VideoProfileType = "Mpeg2422"
	VIDEOPROFILETYPE_MPEG2_MVP VideoProfileType = "Mpeg2Mvp"
	VIDEOPROFILETYPE_VC1_SIMPLE VideoProfileType = "Vc1Simple"
	VIDEOPROFILETYPE_VC1_MAIN VideoProfileType = "Vc1Main"
	VIDEOPROFILETYPE_VC1_ADVANCED VideoProfileType = "Vc1Advanced"
	VIDEOPROFILETYPE_PRO_RES_NORMAL VideoProfileType = "ProResNormal"
	VIDEOPROFILETYPE_PRO_RES_HQ VideoProfileType = "ProResHq"
	VIDEOPROFILETYPE_PRO_RES_LT VideoProfileType = "ProResLt"
	VIDEOPROFILETYPE_PRO_RES_PROXY VideoProfileType = "ProResProxy"
	VIDEOPROFILETYPE_PRO_RES4444 VideoProfileType = "ProRes4444"
	VIDEOPROFILETYPE_HEVC_MAIN VideoProfileType = "HevcMain"
	VIDEOPROFILETYPE_HEVC_MAIN10 VideoProfileType = "HevcMain10"
	VIDEOPROFILETYPE_HEVC_MAIN_STILL VideoProfileType = "HevcMainStill"
	VIDEOPROFILETYPE_PRO_RES4444_XQ VideoProfileType = "ProRes4444Xq"
)