/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type GopOrder string

// List of gop_order
const (
	GOPORDER_DISPLAY GopOrder = "Display"
	GOPORDER_CODED GopOrder = "Coded"
)