/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type UkDppShim string

// List of uk_dpp_shim
const (
	UKDPPSHIM_DPP_AUTO UkDppShim = "DppAuto"
	UKDPPSHIM_DPP_SD UkDppShim = "DppSd"
	UKDPPSHIM_DPP_HD UkDppShim = "DppHd"
)