/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

// Description of the processed media file.
type Media struct {
	Audio []AudioStream `json:"audio,omitempty"`
	Video []VideoStream `json:"video,omitempty"`
	Container Container `json:"container,omitempty"`
}
