/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type SynchronizationEvent struct {
	Timestamp string `json:"timestamp,omitempty"`
	Skew int32 `json:"skew,omitempty"`
	Result string `json:"result,omitempty"`
}
