/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ArrayOfPictureEssenceCoding struct {
	PictureEssenceCoding []PictureEssenceCoding `json:"picture_essence_coding,omitempty"`
}
