/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type StartTcRangeMethod string

// List of start_tc_range_method
const (
	STARTTCRANGEMETHOD_START_TC_AT StartTcRangeMethod = "StartTcAt"
	STARTTCRANGEMETHOD_START_TC_BETWEEN StartTcRangeMethod = "StartTcBetween"
)