/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type EmbeddedXmlDocuments string

// List of embedded_xml_documents
const (
	EMBEDDEDXMLDOCUMENTS_NONE EmbeddedXmlDocuments = "EMBEDDED-XML-NONE"
	EMBEDDEDXMLDOCUMENTS_DM_FOR_PROGRAMMES EmbeddedXmlDocuments = "EMBEDDED-XML-DM-FOR-PROGRAMMES"
)