/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ColorBarStandardType string

// List of color_bar_standard_type
const (
	COLORBARSTANDARDTYPE_ANY_COLOR_BARS ColorBarStandardType = "AnyColorBars"
	COLORBARSTANDARDTYPE_SMPTE_SD ColorBarStandardType = "SmpteSd"
	COLORBARSTANDARDTYPE_SMPTE_HD ColorBarStandardType = "SmpteHd"
	COLORBARSTANDARDTYPE_EBU75 ColorBarStandardType = "Ebu75"
	COLORBARSTANDARDTYPE_EBU100 ColorBarStandardType = "Ebu100"
)