/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type IndexTableTest struct {
	EditRateNum int32 `json:"edit_rate_num,omitempty"`
	EditRateDenom int32 `json:"edit_rate_denom,omitempty"`
	DurationMin int32 `json:"duration_min,omitempty"`
	DurationMax int32 `json:"duration_max,omitempty"`
	EUbyteCountMin int32 `json:"e_ubyte_count_min,omitempty"`
	EUbyteCountMax int32 `json:"e_ubyte_count_max,omitempty"`
	EUbyteCountConstant bool `json:"e_ubyte_count_constant,omitempty"`
	SliceCount int32 `json:"slice_count,omitempty"`
	SingleIndexLocation OptionalFlag `json:"single_index_location,omitempty"`
	SingleEssenceLocation OptionalFlag `json:"single_essence_location,omitempty"`
	ForwardIndexDirection OptionalFlag `json:"forward_index_direction,omitempty"`
	IndexEntryArray OptionalFlag `json:"index_entry_array,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
