/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type OpenOrClosed string

// List of open_or_closed
const (
	OPENORCLOSED_EITHER OpenOrClosed = "Either"
	OPENORCLOSED_OPEN OpenOrClosed = "Open"
	OPENORCLOSED_CLOSED OpenOrClosed = "Closed"
)