/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VideoSegmentDetectionTest struct {
	BlackLevelDefaultOrCustom DefaultOrCustomType `json:"black_level_default_or_custom,omitempty"`
	BlackLevel int32 `json:"black_level,omitempty"`
	PercentageOfFrame int32 `json:"percentage_of_frame,omitempty"`
	MinDurationRequired float64 `json:"min_duration_required,omitempty"`
	MinDurationRequiredSecsOrFrames SecsOrFramesType `json:"min_duration_required_secs_or_frames,omitempty"`
	RequireDigitalSilence bool `json:"require_digital_silence,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
