/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type HdrStandardType string

// List of hdr_standard_type
const (
	HDRSTANDARDTYPE_GENERIC_HDR HdrStandardType = "GenericHdr"
	HDRSTANDARDTYPE_HDR10 HdrStandardType = "Hdr10"
	HDRSTANDARDTYPE_ARIB_B67 HdrStandardType = "AribB67"
)