/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type AudioConfig struct {
	TrackSelectTest TrackSelectTest `json:"track_select_test,omitempty"`
	AudioCodecTest AudioCodecTest `json:"audio_codec_test,omitempty"`
	AudioChannelPositionsTest AudioChannelPositionsTest `json:"audio_channel_positions_test,omitempty"`
	AudioBitDepthTest AudioBitDepthTest `json:"audio_bit_depth_test,omitempty"`
	AudioSampleRateTest AudioSampleRateTest `json:"audio_sample_rate_test,omitempty"`
	AudioBitrateTest AudioBitrateTest `json:"audio_bitrate_test,omitempty"`
	AudioChannelsTest AudioChannelsTest `json:"audio_channels_test,omitempty"`
	AudioLengthTest AudioLengthTest `json:"audio_length_test,omitempty"`
	AudioFrequencyTest AudioFrequencyTest `json:"audio_frequency_test,omitempty"`
	DigitalSilenceWholeTrackTest DigitalSilenceWholeTrackTest `json:"digital_silence_whole_track_test,omitempty"`
	DigitalSilenceAtStartTest DigitalSilenceAtStartEndTest `json:"digital_silence_at_start_test,omitempty"`
	DigitalSilenceAtEndTest DigitalSilenceAtStartEndTest `json:"digital_silence_at_end_test,omitempty"`
	AudioClippingTest AudioClippingTest `json:"audio_clipping_test,omitempty"`
	AudioTransientTest AudioTransientTest `json:"audio_transient_test,omitempty"`
	AudioDialnormTest AudioDialnormTest `json:"audio_dialnorm_test,omitempty"`
	AudioLayoutTest LayoutTest `json:"audio_layout_test,omitempty"`
	AudioPhaseTest AudioPhaseTest `json:"audio_phase_test,omitempty"`
	AudioMinLevelDurationTest AudioMinLevelDurationTest `json:"audio_min_level_duration_test,omitempty"`
	AudioPeakLevelTest AudioPeakLevelTest `json:"audio_peak_level_test,omitempty"`
	AudioLoudnessItest AudioLoudnessItest `json:"audio_loudness_itest,omitempty"`
	AudioLoudnessStest AudioLoudnessStest `json:"audio_loudness_stest,omitempty"`
	AudioLoudnessMtest AudioLoudnessMtest `json:"audio_loudness_mtest,omitempty"`
	AudioLoudnessRangeTest AudioLoudnessRangeTest `json:"audio_loudness_range_test,omitempty"`
	AudioPpmLevelTest AudioPpmLevelTest `json:"audio_ppm_level_test,omitempty"`
	NielsenWatermarkDetectionTest NielsenWatermarkDetectionTest `json:"nielsen_watermark_detection_test,omitempty"`
}
