/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Vidchecker8 struct {
	AudioTests AudioTest `json:"audio_tests,omitempty"`
	FileTests FileConfig `json:"file_tests,omitempty"`
	MxfTest MxfTest `json:"mxf_test,omitempty"`
	VideoTests VideoTest `json:"video_tests,omitempty"`
}
