/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type AudioCodecType string

// List of audio_codec_type
const (
	AUDIOCODECTYPE_MPEG1_MPEG2 AudioCodecType = "Mpeg1Mpeg2"
	AUDIOCODECTYPE_PCM AudioCodecType = "Pcm"
	AUDIOCODECTYPE_AAC AudioCodecType = "Aac"
	AUDIOCODECTYPE_AMR AudioCodecType = "Amr"
	AUDIOCODECTYPE_WMA AudioCodecType = "Wma"
	AUDIOCODECTYPE_DOLBY_AC3 AudioCodecType = "DolbyAc3"
	AUDIOCODECTYPE_DOLBY_DIGITAL_PLUS AudioCodecType = "DolbyDigitalPlus"
	AUDIOCODECTYPE_DOLBY_E AudioCodecType = "DolbyE"
)