/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type VideoCodecType string

// List of video_codec_type
const (
	VIDEOCODECTYPE_MPEG2 VideoCodecType = "Mpeg2"
	VIDEOCODECTYPE_H264 VideoCodecType = "H264"
	VIDEOCODECTYPE_VC1 VideoCodecType = "Vc1"
	VIDEOCODECTYPE_JPEG2000 VideoCodecType = "Jpeg2000"
	VIDEOCODECTYPE_DV25 VideoCodecType = "Dv25"
	VIDEOCODECTYPE_DVC_PRO25 VideoCodecType = "DvcPro25"
	VIDEOCODECTYPE_DVC_PRO50 VideoCodecType = "DvcPro50"
	VIDEOCODECTYPE_DVC_PRO100 VideoCodecType = "DvcPro100"
	VIDEOCODECTYPE_PRO_RES VideoCodecType = "ProRes"
	VIDEOCODECTYPE_MJPEG VideoCodecType = "Mjpeg"
	VIDEOCODECTYPE_DNXHD VideoCodecType = "Dnxhd"
	VIDEOCODECTYPE_UNCOMPRESSED_RGB VideoCodecType = "UncompressedRgb"
	VIDEOCODECTYPE_UNCOMPRESSED_YUV VideoCodecType = "UncompressedYuv"
	VIDEOCODECTYPE_MPEG4 VideoCodecType = "Mpeg4"
	VIDEOCODECTYPE_HUFF_YUV VideoCodecType = "HuffYuv"
	VIDEOCODECTYPE_AVID_MERIDIEN VideoCodecType = "AvidMeridien"
	VIDEOCODECTYPE_HEVC VideoCodecType = "Hevc"
	VIDEOCODECTYPE_CANOPUS VideoCodecType = "Canopus"
	VIDEOCODECTYPE_DNXHR VideoCodecType = "Dnxhr"
)