/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type LowPassFilterType string

// List of low_pass_filter_type
const (
	LOWPASSFILTERTYPE_NO_FILTER LowPassFilterType = "NoFilter"
	LOWPASSFILTERTYPE_EBU2000 LowPassFilterType = "EBU2000"
	LOWPASSFILTERTYPE_EBU2016 LowPassFilterType = "EBU2016"
)