/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type DropFrameType string

// List of drop_frame_type
const (
	DROPFRAMETYPE_NON_DROP DropFrameType = "NonDrop"
	DROPFRAMETYPE_DROP_FRAME DropFrameType = "DropFrame"
)