/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type WrappingType string

// List of wrapping_type
const (
	WRAPPINGTYPE_CLIP_WRAPPED WrappingType = "ClipWrapped"
	WRAPPINGTYPE_FRAME_WRAPPED WrappingType = "FrameWrapped"
)