/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type FileConfig struct {
	ContainerTest ContainerTest `json:"container_test,omitempty"`
	MxfOpTest MxfOpTest `json:"mxf_op_test,omitempty"`
	VideoCodecTest VideoCodecTest `json:"video_codec_test,omitempty"`
	ContainerEssenceConsistencyTest ContainerEssenceConsistencyTest `json:"container_essence_consistency_test,omitempty"`
	ImfConformanceTest ImfConformanceTest `json:"imf_conformance_test,omitempty"`
	NetflixPhotonTest NetflixPhotonTest `json:"netflix_photon_test,omitempty"`
	SpsPpsTest SpsPpsTest `json:"sps_pps_test,omitempty"`
	MbaffTest MbaffTest `json:"mbaff_test,omitempty"`
	CabacTest CabacTest `json:"cabac_test,omitempty"`
	EnhancedSyntaxTest EnhancedSyntaxTest `json:"enhanced_syntax_test,omitempty"`
	FramesizeTest FramesizeTest `json:"framesize_test,omitempty"`
	ChromaSubsamplingTest ChromaSubsamplingTest `json:"chroma_subsampling_test,omitempty"`
	PixelAspectRatioTest PixelAspectRatioTest `json:"pixel_aspect_ratio_test,omitempty"`
	FrameAspectRatioTest FrameAspectRatioTest `json:"frame_aspect_ratio_test,omitempty"`
	CleanApertureTest CleanApertureTest `json:"clean_aperture_test,omitempty"`
	ITunesCompatibilityTest ITunesCompatibilityTest `json:"i_tunes_compatibility_test,omitempty"`
	SingleSampleDescriptionTest SingleSampleDescriptionTest `json:"single_sample_description_test,omitempty"`
	FramerateTest FramerateTest `json:"framerate_test,omitempty"`
	VideoBitDepthTest VideoBitDepthTest `json:"video_bit_depth_test,omitempty"`
	VideoBitRateModeTest BitRateModeTest `json:"video_bit_rate_mode_test,omitempty"`
	VideoBitrateTest VideoBitrateTest `json:"video_bitrate_test,omitempty"`
	GopLengthTest GopLengthTest `json:"gop_length_test,omitempty"`
	AdvancedGopLengthTest AdvancedGopLengthTest `json:"advanced_gop_length_test,omitempty"`
	BufferSizeTest BufferSizeTest `json:"buffer_size_test,omitempty"`
	ClosedCaps608Test TextStreamTest `json:"closed_caps608_test,omitempty"`
	ClosedCaps708Test TextStreamTest `json:"closed_caps708_test,omitempty"`
	DvbSubtitlesTest TextStreamTest `json:"dvb_subtitles_test,omitempty"`
	TeletextTest TextStreamTest `json:"teletext_test,omitempty"`
	CaptionsTest CaptionsTest `json:"captions_test,omitempty"`
	ActiveFormatTest ActiveFormatTest `json:"active_format_test,omitempty"`
	FileBitrateTest FileBitrateTest `json:"file_bitrate_test,omitempty"`
	FileDurationTest FileDurationTest `json:"file_duration_test,omitempty"`
	AudioTracksTest AudioTracksTest `json:"audio_tracks_test,omitempty"`
	UseStartTimecodeTest UseStartTimecodeTest `json:"use_start_timecode_test,omitempty"`
	StartTimecodeTest StartTimecodeTest `json:"start_timecode_test,omitempty"`
	DontCopyAvDelayTest DontCopyAvDelayTest `json:"dont_copy_av_delay_test,omitempty"`
	ContainerDropFrameTest DropFrameTest `json:"container_drop_frame_test,omitempty"`
	VideoDropFrameTest DropFrameTest `json:"video_drop_frame_test,omitempty"`
	TimecodeContinuityTest TimecodeContinuityTest `json:"timecode_continuity_test,omitempty"`
}
