/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type StartTimecodeTest struct {
	RangeMethod StartTcRangeMethod `json:"range_method,omitempty"`
	Hours int32 `json:"hours,omitempty"`
	Minutes int32 `json:"minutes,omitempty"`
	Seconds int32 `json:"seconds,omitempty"`
	Frames int32 `json:"frames,omitempty"`
	FramesTolerance int32 `json:"frames_tolerance,omitempty"`
	EndHours int32 `json:"end_hours,omitempty"`
	EndMinutes int32 `json:"end_minutes,omitempty"`
	EndSeconds int32 `json:"end_seconds,omitempty"`
	EndFrames int32 `json:"end_frames,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
