/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type BlockinessTest struct {
	QualityLevel int32 `json:"quality_level,omitempty"`
	MaxTimeBelowQuality float64 `json:"max_time_below_quality,omitempty"`
	MaxTimeBelowQualitySecsOrFrames SecsOrFramesType `json:"max_time_below_quality_secs_or_frames,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
