/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type PpmMode string

// List of ppm_mode
const (
	PPMMODE_PPM_MODE_M3 PpmMode = "PpmModeM3"
	PPMMODE_PPM_MODE_M6 PpmMode = "PpmModeM6"
	PPMMODE_PPM_MODE_AB PpmMode = "PpmModeAb"
)