/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type SoundEssenceCoding string

// List of sound_essence_coding
const (
	SOUNDESSENCECODING_PCM SoundEssenceCoding = "SOUND-PCM"
	SOUNDESSENCECODING_DEFAULT SoundEssenceCoding = "SOUND-DEFAULT"
	SOUNDESSENCECODING_DOLBY_E SoundEssenceCoding = "SOUND-DOLBY-E"
)