/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ToneType string

// List of tone_type
const (
	TONETYPE_CONTINUOUS ToneType = "Continuous"
	TONETYPE_EBU1000_HZ ToneType = "Ebu1000Hz"
	TONETYPE_EBU440_HZ ToneType = "Ebu440Hz"
	TONETYPE_GLITS1000_HZ ToneType = "Glits1000Hz"
	TONETYPE_GLITS2000_HZ ToneType = "Glits2000Hz"
	TONETYPE_BLITS ToneType = "Blits"
	TONETYPE_EBU_MULTICHANNEL ToneType = "EbuMultichannel"
)