/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type AudioPhaseTest struct {
	MinimumPhaseEnabled bool `json:"minimum_phase_enabled,omitempty"`
	MinimumPhase float64 `json:"minimum_phase,omitempty"`
	MeanPhaseEnabled bool `json:"mean_phase_enabled,omitempty"`
	MeanPhase float64 `json:"mean_phase,omitempty"`
	MaxMeanPhaseEnabled bool `json:"max_mean_phase_enabled,omitempty"`
	MaxMeanPhase float64 `json:"max_mean_phase,omitempty"`
	Channels Channels `json:"channels,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
