/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type BitRateMode string

// List of bit_rate_mode
const (
	BITRATEMODE_CBR BitRateMode = "CBR"
	BITRATEMODE_VBR BitRateMode = "VBR"
)