/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type MxfOpTest struct {
	Op OperationalPattern `json:"op,omitempty"`
	RequireClosed bool `json:"require_closed,omitempty"`
	RequireComplete bool `json:"require_complete,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
