/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type LetterboxingTest struct {
	RatioOrLines RatioOrLinesType `json:"ratio_or_lines,omitempty"`
	RatioHorizontal int32 `json:"ratio_horizontal,omitempty"`
	RatioVertical int32 `json:"ratio_vertical,omitempty"`
	LinesTopAndBottom int32 `json:"lines_top_and_bottom,omitempty"`
	LinesLeftAndRight int32 `json:"lines_left_and_right,omitempty"`
	Tolerance int32 `json:"tolerance,omitempty"`
	BlackLevelDefaultOrCustom DefaultOrCustomType `json:"black_level_default_or_custom,omitempty"`
	BlackLevel int32 `json:"black_level,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
