/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Proxy struct {
	Status string `json:"status,omitempty"`
	Progress int32 `json:"progress,omitempty"`
	Url string `json:"url,omitempty"`
	Id string `json:"id,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
}
