/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type VideoSubDescriptorType string

// List of video_sub_descriptor_type
const (
	VIDEOSUBDESCRIPTORTYPE_AVC_SUB_DESCRIPTOR VideoSubDescriptorType = "AvcSubDescriptor"
)