/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ChanPos string

// List of chan_pos
const (
	CHANPOS_ANY ChanPos = "Any"
	CHANPOS_L ChanPos = "L"
	CHANPOS_R ChanPos = "R"
	CHANPOS_C ChanPos = "C"
	CHANPOS_LFE ChanPos = "Lfe"
	CHANPOS_LS ChanPos = "Ls"
	CHANPOS_RS ChanPos = "Rs"
	CHANPOS_LT ChanPos = "Lt"
	CHANPOS_RT ChanPos = "Rt"
)