/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type LocationTest struct {
	Header OptionalFlag `json:"header,omitempty"`
	Body OptionalFlag `json:"body,omitempty"`
	Footer OptionalFlag `json:"footer,omitempty"`
	HeaderOrBodyOrFooter bool `json:"header_or_body_or_footer,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
