/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type RatioOrLinesType string

// List of ratio_or_lines_type
const (
	RATIOORLINESTYPE_RATIO RatioOrLinesType = "Ratio"
	RATIOORLINESTYPE_LINES RatioOrLinesType = "Lines"
)