/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Alert struct {
	Level string `json:"level,omitempty"`
	// Extra information for an alert.
	Info string `json:"info,omitempty"`
	// Start time of alert.
	Begin float32 `json:"begin,omitempty"`
	// End time of alert.
	End float32 `json:"end,omitempty"`
	Stream int32 `json:"stream,omitempty"`
	Detail string `json:"detail,omitempty"`
}
