/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type PSeParameterType string

// List of p_se_parameter_type
const (
	PSEPARAMETERTYPE_PSE_STANDARD PSeParameterType = "PSEStandard"
	PSEPARAMETERTYPE_PSE_STRICT PSeParameterType = "PSEStrict"
)