/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type MxfTest struct {
	As11UkDppMetadataTest As11UkDppMetadataTest `json:"as11_uk_dpp_metadata_test,omitempty"`
	As11XprofileTest As11XprofileTest `json:"as11_xprofile_test,omitempty"`
	OperationalPatternTest OperationalPatternTest `json:"operational_pattern_test,omitempty"`
	VersionTest VersionTest `json:"version_test,omitempty"`
	KagSizeTest KagSizeTest `json:"kag_size_test,omitempty"`
	RunInTest RunInTest `json:"run_in_test,omitempty"`
	WrappingTypeTest WrappingTypeTest `json:"wrapping_type_test,omitempty"`
	SourcePackageTimecodeTest TimecodeTrackTest `json:"source_package_timecode_test,omitempty"`
	MaterialPackageTimecodeTest TimecodeTrackTest `json:"material_package_timecode_test,omitempty"`
	SdtiTimecodeContinuityTest SdtiTimecodeContinuityTest `json:"sdti_timecode_continuity_test,omitempty"`
	IndexTableTest IndexTableTest `json:"index_table_test,omitempty"`
	IndexTableLocationTest LocationTest `json:"index_table_location_test,omitempty"`
	HeaderPartitionStatusTest PartitionStatusTest `json:"header_partition_status_test,omitempty"`
	HeaderFillTest HeaderFillTest `json:"header_fill_test,omitempty"`
	HeaderByteCountTest HeaderByteCountTest `json:"header_byte_count_test,omitempty"`
	BodyPartitionStatusTest PartitionStatusTest `json:"body_partition_status_test,omitempty"`
	BodyPartitionCountTest LongMinMaxTest `json:"body_partition_count_test,omitempty"`
	BodyPartitionDurationTest LongMinMaxTest `json:"body_partition_duration_test,omitempty"`
	BodyPartitionLengthTest LongMinMaxTest `json:"body_partition_length_test,omitempty"`
	FooterPartitionStatusTest PartitionStatusTest `json:"footer_partition_status_test,omitempty"`
	RipPresentTest RipPresentTest `json:"rip_present_test,omitempty"`
	EssenceLocationTest LocationTest `json:"essence_location_test,omitempty"`
	PictureEssenceContainerLabelTest MxfKeyTest `json:"picture_essence_container_label_test,omitempty"`
	PictureElementKeyTest MxfKeyTest `json:"picture_element_key_test,omitempty"`
	PictureEssenceCodingTest PictureEssenceCodingTest `json:"picture_essence_coding_test,omitempty"`
	FieldDominanceTest FieldDominanceTest `json:"field_dominance_test,omitempty"`
	SignalStandardTest SignalStandardTest `json:"signal_standard_test,omitempty"`
	PictureOffsetsTest PictureOffsetsTest `json:"picture_offsets_test,omitempty"`
	ActiveFormatDescriptorTest ActiveFormatDescriptorTest `json:"active_format_descriptor_test,omitempty"`
	ColorSitingTest ColorSitingTest `json:"color_siting_test,omitempty"`
	PaddingBitsTest PaddingBitsTest `json:"padding_bits_test,omitempty"`
	ColorRangeTest ColorRangeTest `json:"color_range_test,omitempty"`
	SubsamplingTest SubsamplingTest `json:"subsampling_test,omitempty"`
	ComponentDepthTest ComponentDepthTest `json:"component_depth_test,omitempty"`
	StoredFrameSizeTest PicFrameSizeTest `json:"stored_frame_size_test,omitempty"`
	SampledFrameSizeTest PicFrameSizeTest `json:"sampled_frame_size_test,omitempty"`
	DisplayFrameSizeTest PicFrameSizeTest `json:"display_frame_size_test,omitempty"`
	AspectRatioTest RatioTest `json:"aspect_ratio_test,omitempty"`
	PicEditRateTest RatioTest `json:"pic_edit_rate_test,omitempty"`
	ReferenceLevelsTest ReferenceLevelsTest `json:"reference_levels_test,omitempty"`
	VideoLineMapTest VideoLineMapTest `json:"video_line_map_test,omitempty"`
	VideoDescriptorTest VideoDescriptorTest `json:"video_descriptor_test,omitempty"`
	VideoSubDescriptorTest VideoSubDescriptorTest `json:"video_sub_descriptor_test,omitempty"`
	MpegBitRateTest LongMinMaxTest `json:"mpeg_bit_rate_test,omitempty"`
	MpegIdenticalGopTest ExtendedBoolValueTest `json:"mpeg_identical_gop_test,omitempty"`
	MpegMaxGopTest LongMinMaxTest `json:"mpeg_max_gop_test,omitempty"`
	MpegMaxBpicCountTest LongMinMaxTest `json:"mpeg_max_bpic_count_test,omitempty"`
	MpegConstantBpicFlagTest ExtendedBoolValueTest `json:"mpeg_constant_bpic_flag_test,omitempty"`
	MpegCodedContentTest LongValueTest `json:"mpeg_coded_content_test,omitempty"`
	AvcDecodingDelayTest LongValueTest `json:"avc_decoding_delay_test,omitempty"`
	AvcCodedContentKindTest AvcCodedContentKindTest `json:"avc_coded_content_kind_test,omitempty"`
	AvcIdenticalGopIndicatorTest BoolValueTest `json:"avc_identical_gop_indicator_test,omitempty"`
	AvcMaxGopSizeTest LongValueTest `json:"avc_max_gop_size_test,omitempty"`
	AvcMaxBpicCountTest LongValueTest `json:"avc_max_bpic_count_test,omitempty"`
	AvcMaxBitRateTest LongMinMaxTest `json:"avc_max_bit_rate_test,omitempty"`
	AvcAvgBitRateTest LongMinMaxTest `json:"avc_avg_bit_rate_test,omitempty"`
	AvcSpsPpsTest AvcSpsPpsTest `json:"avc_sps_pps_test,omitempty"`
	SoundEssenceContainerLabelTest MxfKeyTest `json:"sound_essence_container_label_test,omitempty"`
	SoundElementKeyTest MxfKeyTest `json:"sound_element_key_test,omitempty"`
	SoundEssenceCodingTest SoundEssenceCodingTest `json:"sound_essence_coding_test,omitempty"`
	AudioSamplingRateTest RatioTest `json:"audio_sampling_rate_test,omitempty"`
	AudioLockedTest BoolValueTest `json:"audio_locked_test,omitempty"`
	DialnormTest LongMinMaxTest `json:"dialnorm_test,omitempty"`
	AudioRefLevelTest LongMinMaxTest `json:"audio_ref_level_test,omitempty"`
	ChannelCountTest LongValueTest `json:"channel_count_test,omitempty"`
	QuantizationBitsTest LongValueTest `json:"quantization_bits_test,omitempty"`
	AudioAvgBytesPerSecTest LongMinMaxTest `json:"audio_avg_bytes_per_sec_test,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
