/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type OptionalFlag string

// List of optional_flag
const (
	OPTIONALFLAG__0 OptionalFlag = "0"
	OPTIONALFLAG__1 OptionalFlag = "1"
	OPTIONALFLAG_EITHER OptionalFlag = "Either"
)