/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type MxfKeyTest struct {
	UseCustom bool `json:"use_custom,omitempty"`
	PredefinedKey string `json:"predefined_key,omitempty"`
	CustomKey string `json:"custom_key,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
