/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type NielsenWatermarkDetectionTest struct {
	Naes2Enabled bool `json:"naes2_enabled,omitempty"`
	Naes2SidsAnyOrSpecific SidsAnyOrSpecific `json:"naes2_sids_any_or_specific,omitempty"`
	Naes2Sids string `json:"naes2_sids,omitempty"`
	Naes2HighFrequencyEnabled bool `json:"naes2_high_frequency_enabled,omitempty"`
	Naes2HighFrequencySidsAnyOrSpecific SidsAnyOrSpecific `json:"naes2_high_frequency_sids_any_or_specific,omitempty"`
	Naes2HighFrequencySids string `json:"naes2_high_frequency_sids,omitempty"`
	Naes6Enabled bool `json:"naes6_enabled,omitempty"`
	Naes6SidsAnyOrSpecific SidsAnyOrSpecific `json:"naes6_sids_any_or_specific,omitempty"`
	Naes6Sids string `json:"naes6_sids,omitempty"`
	Channels Channels `json:"channels,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
