/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VideoStream struct {
	// Video stream duration measured in seconds.
	Duration float32 `json:"duration,omitempty"`
	Codec string `json:"codec,omitempty"`
	Width int32 `json:"width,omitempty"`
	Height int32 `json:"height,omitempty"`
	// Video stream bitrate measured in bps
	Bitrate int32 `json:"bitrate,omitempty"`
	Fps float32 `json:"fps,omitempty"`
}
