/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type FileBitrateTest struct {
	FileBitrateLower float64 `json:"file_bitrate_lower,omitempty"`
	FileBitrateUpper float64 `json:"file_bitrate_upper,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
