/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type CadenceType string

// List of cadence_type
const (
	CADENCETYPE_CADENCE_UNKNOWN CadenceType = "CadenceUnknown"
	CADENCETYPE_CADENCE_PROGRESSIVE CadenceType = "CadenceProgressive"
	CADENCETYPE_CADENCE_TFF CadenceType = "CadenceTFF"
	CADENCETYPE_CADENCE_BFF CadenceType = "CadenceBFF"
	CADENCETYPE_CADENCE23_TFF CadenceType = "Cadence23TFF"
	CADENCETYPE_CADENCE23_BFF CadenceType = "Cadence23BFF"
	CADENCETYPE_CADENCE24TO25_PROG CadenceType = "Cadence24to25Prog"
	CADENCETYPE_CADENCE24TO25_TFF CadenceType = "Cadence24to25TFF"
	CADENCETYPE_CADENCE24TO25_BFF CadenceType = "Cadence24to25BFF"
	CADENCETYPE_CADENCE2224 CadenceType = "Cadence2224"
	CADENCETYPE_CADENCE2332_TFF CadenceType = "Cadence2332TFF"
	CADENCETYPE_CADENCE2332_BFF CadenceType = "Cadence2332BFF"
	CADENCETYPE_CADENCE25TO30_TFF CadenceType = "Cadence25to30TFF"
	CADENCETYPE_CADENCE25TO30_BFF CadenceType = "Cadence25to30BFF"
	CADENCETYPE_CADENCE25TO30_PROG CadenceType = "Cadence25to30Prog"
)