/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type PictureEssenceConstraints string

// List of picture_essence_constraints
const (
	PICTUREESSENCECONSTRAINTS_NONE PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-NONE"
	PICTUREESSENCECONSTRAINTS_X1_AVC_ST381_3 PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-X1-AVC-ST381-3"
	PICTUREESSENCECONSTRAINTS_X2_RP2020 PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-X2-RP2020"
	PICTUREESSENCECONSTRAINTS_X3_AVC_ST381_3 PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-X3-AVC-ST381-3"
	PICTUREESSENCECONSTRAINTS_X4_AVC_ST381_3 PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-X4-AVC-ST381-3"
	PICTUREESSENCECONSTRAINTS_X9_AVC PictureEssenceConstraints = "PIC-ESSENCE-CONSTRAINTS-X9-AVC"
)