/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type CadenceTest struct {
	CheckCadence bool `json:"check_cadence,omitempty"`
	CadenceRequired CadenceType `json:"cadence_required,omitempty"`
	CheckCadenceBreaks bool `json:"check_cadence_breaks,omitempty"`
	ReportCadence bool `json:"report_cadence,omitempty"`
	CheckForPoorCadence bool `json:"check_for_poor_cadence,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
