/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type FileFormatSpecificationIdentificationLabel string

// List of file_format_specification_identification_label
const (
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_NONE FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-NONE"
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_X1_FF1_WIP FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-X1-FF1-WIP"
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_X2_FF2 FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-X2-FF2"
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_X3_FF5_WIP FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-X3-FF5-WIP"
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_X4_FF6_WIP FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-X4-FF6-WIP"
	FILEFORMATSPECIFICATIONIDENTIFICATIONLABEL_X9_FF11_WIP FileFormatSpecificationIdentificationLabel = "FILE-FORMAT-SPEC-ID-X9-FF11-WIP"
)