/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type VidChecker8JobData struct {
	Url string `json:"url,omitempty"`
	Payload string `json:"payload,omitempty"`
	Options Vidchecker8 `json:"options,omitempty"`
}
