/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type FrameAspectRatioTest struct {
	FrameAspectRatioNumerator int32 `json:"frame_aspect_ratio_numerator,omitempty"`
	FrameAspectRatioDenominator int32 `json:"frame_aspect_ratio_denominator,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
