/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ExtendedBool string

// List of extended_bool
const (
	EXTENDEDBOOL_TRUE ExtendedBool = "true"
	EXTENDEDBOOL_FALSE ExtendedBool = "false"
	EXTENDEDBOOL_EITHER ExtendedBool = "Either"
	EXTENDEDBOOL_NOT_PRESENT ExtendedBool = "NotPresent"
)