/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type InlineResponse200 struct {
	ProjectName string `json:"project_name,omitempty"`
	ProjectId string `json:"project_id,omitempty"`
}
