/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Job struct {
	Id string `json:"id,omitempty"`
	ProjectId string `json:"project_id,omitempty"`
	Status string `json:"status,omitempty"`
	State string `json:"state,omitempty"`
	Duration int32 `json:"duration,omitempty"`
	Type string `json:"type,omitempty"`
	Progress int32 `json:"progress,omitempty"`
	Filename string `json:"filename,omitempty"`
	SourceUrl string `json:"source_url,omitempty"`
	CreatedAt string `json:"created_at,omitempty"`
	UpdatedAt string `json:"updated_at,omitempty"`
	ErrorClass string `json:"error_class,omitempty"`
	ErrorMessage string `json:"error_message,omitempty"`
	Payload string `json:"payload,omitempty"`
	Details map[string]interface{} `json:"details,omitempty"`
}
