/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type OperationalPattern string

// List of operational_pattern
const (
	OPERATIONALPATTERN_OP_ATOM OperationalPattern = "OpAtom"
	OPERATIONALPATTERN_OP1A OperationalPattern = "Op1a"
	OPERATIONALPATTERN_OP1B OperationalPattern = "Op1b"
	OPERATIONALPATTERN_OP1C OperationalPattern = "Op1c"
	OPERATIONALPATTERN_OP2A OperationalPattern = "Op2a"
	OPERATIONALPATTERN_OP2B OperationalPattern = "Op2b"
	OPERATIONALPATTERN_OP2C OperationalPattern = "Op2c"
	OPERATIONALPATTERN_OP3A OperationalPattern = "Op3a"
	OPERATIONALPATTERN_OP3B OperationalPattern = "Op3b"
	OPERATIONALPATTERN_OP3C OperationalPattern = "Op3c"
)