/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type ColourBarsTest struct {
	ColorBarStandard ColorBarStandardType `json:"color_bar_standard,omitempty"`
	Tolerance int32 `json:"tolerance,omitempty"`
	TimeRangeEnabled bool `json:"time_range_enabled,omitempty"`
	StartTime float64 `json:"start_time,omitempty"`
	EndTime float64 `json:"end_time,omitempty"`
	RangeTolerance float64 `json:"range_tolerance,omitempty"`
	TimeSecsOrFrames SecsOrFramesType `json:"time_secs_or_frames,omitempty"`
	NotAtAnyOtherTime bool `json:"not_at_any_other_time,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
