/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type AvcContentKind string

// List of avc_content_kind
const (
	AVCCONTENTKIND_UNKNOWN AvcContentKind = "Unknown"
	AVCCONTENTKIND_PROGRESSIVE_FRAME AvcContentKind = "ProgressiveFrame"
	AVCCONTENTKIND_INTERLACED_FIELD AvcContentKind = "InterlacedField"
	AVCCONTENTKIND_INTERLACED_FRAME AvcContentKind = "InterlacedFrame"
	AVCCONTENTKIND_INTERLACED_FRAME_AND_FIELD AvcContentKind = "InterlacedFrameAndField"
	AVCCONTENTKIND_ANY AvcContentKind = "Any"
)