/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type BlackFrameTest struct {
	LevelDefaultOrCustom DefaultOrCustomType `json:"level_default_or_custom,omitempty"`
	Level int32 `json:"level,omitempty"`
	PercentageOfFrame int32 `json:"percentage_of_frame,omitempty"`
	StartRangeEnabled bool `json:"start_range_enabled,omitempty"`
	StartTime float64 `json:"start_time,omitempty"`
	EndTime float64 `json:"end_time,omitempty"`
	StartRangeTolerance float64 `json:"start_range_tolerance,omitempty"`
	TimeSecsOrFrames SecsOrFramesType `json:"time_secs_or_frames,omitempty"`
	EndRangeEnabled bool `json:"end_range_enabled,omitempty"`
	EndRange float64 `json:"end_range,omitempty"`
	EndRangeTolerance float64 `json:"end_range_tolerance,omitempty"`
	EndSecsOrFrames SecsOrFramesType `json:"end_secs_or_frames,omitempty"`
	NotAtAnyOtherTime bool `json:"not_at_any_other_time,omitempty"`
	MaxTimeAllowed float64 `json:"max_time_allowed,omitempty"`
	MaxTimeAllowedSecsOrFrames SecsOrFramesType `json:"max_time_allowed_secs_or_frames,omitempty"`
	MaxTimeAtStart bool `json:"max_time_at_start,omitempty"`
	MaxTimeAllowedAtStart float64 `json:"max_time_allowed_at_start,omitempty"`
	MaxTimeAllowedAtStartSecsOrFrames SecsOrFramesType `json:"max_time_allowed_at_start_secs_or_frames,omitempty"`
	MaxTimeAtEnd bool `json:"max_time_at_end,omitempty"`
	MaxTimeAllowedAtEnd float64 `json:"max_time_allowed_at_end,omitempty"`
	MaxTimeAllowedAtEndSecsOrFrames SecsOrFramesType `json:"max_time_allowed_at_end_secs_or_frames,omitempty"`
	RejectOnError bool `json:"reject_on_error,omitempty"`
	DoCorrection bool `json:"do_correction,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
