/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type Container struct {
	Type string `json:"type,omitempty"`
	// File bitrate measured in bps
	Bitrate int32 `json:"bitrate,omitempty"`
}
