/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type ContainerType string

// List of container_type
const (
	CONTAINERTYPE_NONE ContainerType = "None"
	CONTAINERTYPE_TS ContainerType = "Ts"
	CONTAINERTYPE_PS ContainerType = "Ps"
	CONTAINERTYPE_MXF ContainerType = "Mxf"
	CONTAINERTYPE_MP4 ContainerType = "Mp4"
	CONTAINERTYPE_MOV ContainerType = "Mov"
	CONTAINERTYPE_ASF ContainerType = "Asf"
	CONTAINERTYPE_AVI ContainerType = "Avi"
	CONTAINERTYPE_LXF ContainerType = "Lxf"
	CONTAINERTYPE_GXF ContainerType = "Gxf"
	CONTAINERTYPE_FLASH ContainerType = "Flash"
	CONTAINERTYPE_MATROSKA ContainerType = "Matroska"
	CONTAINERTYPE_IMF ContainerType = "Imf"
	CONTAINERTYPE_DPX ContainerType = "Dpx"
	CONTAINERTYPE_OPEN_EXR ContainerType = "OpenExr"
)