/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc

type LayoutTest struct {
	LayoutType LayoutType `json:"layout_type,omitempty"`
	StartDuration float64 `json:"start_duration,omitempty"`
	StartDurationSecsOrFrames SecsOrFramesType `json:"start_duration_secs_or_frames,omitempty"`
	EndDuration float64 `json:"end_duration,omitempty"`
	EndDurationSecsOrFrames SecsOrFramesType `json:"end_duration_secs_or_frames,omitempty"`
	StartEnabled bool `json:"start_enabled,omitempty"`
	StartHours int32 `json:"start_hours,omitempty"`
	StartMinutes int32 `json:"start_minutes,omitempty"`
	StartSeconds int32 `json:"start_seconds,omitempty"`
	StartFrames int32 `json:"start_frames,omitempty"`
	EndEnabled bool `json:"end_enabled,omitempty"`
	EndHours int32 `json:"end_hours,omitempty"`
	EndMinutes int32 `json:"end_minutes,omitempty"`
	EndSeconds int32 `json:"end_seconds,omitempty"`
	EndFrames int32 `json:"end_frames,omitempty"`
	Checked bool `json:"checked,omitempty"`
}
