/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type MxfFieldDominance string

// List of mxf_field_dominance
const (
	MXFFIELDDOMINANCE_FD_ABSENT MxfFieldDominance = "FdAbsent"
	MXFFIELDDOMINANCE_FD_FIRST MxfFieldDominance = "FdFirst"
	MXFFIELDDOMINANCE_FD_SECOND MxfFieldDominance = "FdSecond"
)