/*
 * Qc API
 *
 * Qc API
 *
 * API version: 3.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package qc
type MustOrMustNot string

// List of must_or_must_not
const (
	MUSTORMUSTNOT_MUST MustOrMustNot = "Must"
	MUSTORMUSTNOT_MUST_NOT MustOrMustNot = "MustNot"
)