/*
 * Qc API
 *
 * QC API
 *
 * API version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

// JSON with specific options
type Options struct {
}
