/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.3
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Project struct {

	// A unique identifier of a Project.
	Id string `json:"id,omitempty"`

	// Human-readable identifier of a Project.
	Name string `json:"name,omitempty"`

	// Project status.
	Status string `json:"status,omitempty"`

	// Name of QC template.
	Template string `json:"template,omitempty"`

	// JSON with specific options
	Options map[string]interface{} `json:"options,omitempty"`
}
