/* 
 * Qc API
 *
 * QC API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package qc

type Project struct {

	// A unique identifier of a Project.
	Id string `json:"id,omitempty"`

	// Human-readable identifier of a Project.
	Name string `json:"name,omitempty"`

	// Project status.
	Status string `json:"status,omitempty"`

	// Name of QC template 2.
	Template string `json:"template,omitempty"`

	// JSON with specific options
	Options string `json:"options,omitempty"`
}
