/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Proxy struct {

	Status string `json:"status,omitempty"`

	Progress int32 `json:"progress,omitempty"`

	Url string `json:"url,omitempty"`

	Id string `json:"id,omitempty"`

	UpdatedAt string `json:"updated_at,omitempty"`
}
