/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.3
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type SynchronizationEvent struct {

	Timestamp string `json:"timestamp,omitempty"`

	Skew int32 `json:"skew,omitempty"`

	Result string `json:"result,omitempty"`
}
