/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type Template struct {

	Name string `json:"name,omitempty"`

	Type_ string `json:"type,omitempty"`

	Description string `json:"description,omitempty"`

	Produces map[string]string `json:"produces,omitempty"`

	Takes map[string]string `json:"takes,omitempty"`
}
