/*
 * Qc API
 *
 * QC API
 *
 * API version: 2.0.1
 * Contact: cloudsupport@telestream.net
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package qc

type VideoUploadBody struct {

	// Size of the file that will be uploaded in `bytes`.
	FileSize int64 `json:"file_size"`

	// Name of the file that will be uploaded.
	FileName string `json:"file_name"`

	// A list of names of additional files that will be uploaded.
	ExtraFiles []ExtraFile `json:"extra_files,omitempty"`

	// A comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings will created right away.
	Profiles string `json:"profiles,omitempty"`

	MultiChunk bool `json:"multi_chunk,omitempty"`
}
